version: "3.8"
services:
  #apache2
  app:
    build: .
    ports:
      - "8000:80"
    tty: true
    volumes:
      - ./:/app
    networks:
      - network
#Network
networks:
  network:
#Volumes
#volumes:
#  db-data:
#  log: