index:
    uri: /
    controller: Controller\HomeController
    httpMethod: [GET]

level-one:
    uri: /level/1
    controller: Controller\Level\LevelOneController
    httpMethod: [GET, POST]
level-two:
    uri: /level/2
    controller: Controller\Level\LevelTwoController
    httpMethod: [GET, POST]
level-three:
    uri: /level/3
    controller: Controller\Level\LevelThreeController
    httpMethod: [GET, POST]
level-four:
    uri: /level/4
    controller: Controller\Level\LevelFourController
    httpMethod: [GET, POST]
level-five:
    uri: /level/5
    controller: Controller\Level\LevelFiveController
    httpMethod: [GET, POST]
